-- local ok, _ = pcall(require, "nvim-treesitter")
-- if not ok then
-- 	return
-- end
--
-- -- local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
--
-- -- local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
-- -- parser_config.vhdl = {
-- -- 	install_info = {
-- -- 		-- url = "~/projects/tree-sitter-zimbu", -- local path or git repo
-- -- 		url = "$HOME/Projects/tree-sitter-vhdl", -- local path or git repo
-- -- 		files = { "src/parser.c" },
-- -- 		-- optional entries:
-- -- 		branch = "main", -- default branch in case of git repo if different from master
-- -- 		generate_requires_npm = false, -- if stand-alone parser without npm dependencies
-- -- 		requires_generate_from_grammar = false, -- if folder contains pre-generated src/parser.c
-- -- 	},
-- -- 	filetype = "vhdl", -- if filetype does not match the parser name
-- -- }
--
-- -- parser_config.vhdl = {
-- -- 	install_info = {
-- -- 		url = "$HOME/Projects/tree-sitter-vhdl", -- local path or git repo
-- -- 		files = { "src/parser.c" },
-- -- 	},
-- -- 	filetype = "vhd", -- if filetype does not agrees with parser name
-- -- 	used_by = { "vhdl", "vho" }, -- additional filetypes that use this parser
-- -- }
--
-- require("nvim-treesitter.configs").setup({
-- 	playground = {
-- 		enable = true,
-- 		disable = {},
-- 		updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
-- 		persist_queries = false, -- Whether the query persists across vim sessions
-- 		keybindings = {
-- 			toggle_query_editor = "o",
-- 			toggle_hl_groups = "i",
-- 			toggle_injected_languages = "t",
-- 			toggle_anonymous_nodes = "a",
-- 			toggle_language_display = "I",
-- 			focus_language = "f",
-- 			unfocus_language = "F",
-- 			update = "R",
-- 			goto_node = "<cr>",
-- 			show_help = "?",
-- 		},
-- 	},
-- })
--
-- -- Treesitter configuration
-- -- Parsers must be installed manually via :TSInstall
-- require("nvim-treesitter.configs").setup({
-- 	highlight = {
-- 		enable = true, -- false will disable the whole extension
-- 	},
-- 	incremental_selection = {
-- 		enable = true,
-- 		keymaps = {
-- 			init_selection = "gnn",
-- 			node_incremental = "grn",
-- 			scope_incremental = "grc",
-- 			node_decremental = "grm",
-- 		},
-- 	},
-- 	indent = {
-- 		enable = true,
-- 	},
-- 	textobjects = {
-- 		select = {
-- 			enable = true,
-- 			lookahead = true, -- Automatically jump forward to textobj, similar to targets.vim
-- 			keymaps = {
-- 				-- You can use the capture groups defined in textobjects.scm
-- 				["af"] = "@function.outer",
-- 				["if"] = "@function.inner",
-- 				["ac"] = "@class.outer",
-- 				["ic"] = "@class.inner",
-- 			},
-- 		},
-- 		move = {
-- 			enable = true,
-- 			set_jumps = true, -- whether to set jumps in the jumplist
-- 			goto_next_start = {
-- 				["]m"] = "@function.outer",
-- 				["]]"] = "@class.outer",
-- 			},
-- 			goto_next_end = {
-- 				["]M"] = "@function.outer",
-- 				["]["] = "@class.outer",
-- 			},
-- 			goto_previous_start = {
-- 				["[m"] = "@function.outer",
-- 				["[["] = "@class.outer",
-- 			},
-- 			goto_previous_end = {
-- 				["[M"] = "@function.outer",
-- 				["[]"] = "@class.outer",
-- 			},
-- 		},
-- 	},
-- })
